### PR TITLE
used latest version of mongodb for tests bec of npm audit vulnerability

### PR DESCRIPTION
**Pull request by montumodi**
used latest version of mongodb for tests bec of npm audit vulnerability. Although it is in dev dependecy so doesn't really impact any one but still if someone is planning to do some dev on local, it will throw error.

### CODE REVIEW

**Comment by montumodi** [comment]
I am not sure why but tests are breaking when they run in context of docker. If I run them directly from my mac book, they are fine. Not sure what is wrong.

**Comment by montumodi** [comment]
@ZJONSSON The tests are fine now. If you are happy to merge it.

**Comment by ZJONSSON** [comment]
Thanks @montumodi excellent - can you confirm if this is a breaking change? (i.e. whether we bump major/minor/patch)

**Comment by montumodi** [comment]
We should be ok as I have just changed tests i.e dev dependency. 

Also if you see mongo driver 2 and 3 are backward compatible. https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility

**Comment by montumodi** [comment]
@ZJONSSON Did you get a chance to look in to this? I hope my reply has answered your query

**Comment by montumodi** [comment]
@ZJONSSON checking again to see if this PR is all good to be merged.

**Comment by ZJONSSON** [comment]
published as `+ etl@0.6.12`   thanks @montumodi @jbreckman

**Pull request merged**
