### PR TITLE
Fixed postgres upsert and included new tests for upsert functionality.

### LINKED ISSUE #98: Postgres upsert non-functional.
Feeding a stream containing existing Postgres pkeys to etl.postgres.upsert results in a duplicate key error, instead of an upsert statement. Manually adding the primary keys to the postgres script.js file and removing the "IF" statement around it (line 100) allows it to work. It would appear that primary keys are not properly being grabbed/fed to this function. 

I may attempt to troubleshoot if I have time, but I'm just bringing it to your attention.

ETL Pipe:
etl.postgres.upsert(pool,'public','testdumps',{concurrency:4 });
Error when existing record piped to above:
ERROR: duplicate key value violates unique constraint "testdumps_pkey"

### PR DESCRIPTION
**Pull request by Go2ClassPoorYorick**
Postgres constructor attempts to call "this.upsert" before setting this.upsert = options.upsert, resulting in this.pkeys never being called.

Fixes #98

### CODE REVIEW

**Comment by ZJONSSON** [comment]
Awesome, thank you  @Go2ClassPoorYorick  - can you create or amend a test that would fail on master but work with this fix?

**Comment by Go2ClassPoorYorick** [comment]
> Awesome, thank you @Go2ClassPoorYorick - can you create or amend a test that would fail on master but work with this fix?

I'm unsure how to go about this or don't understand the question- 

My setup was just a PgSQL DB with a PKEY as an ID field from a rest API I was syncing from. Simply attempting to insert an existing record using the etl.upsert method should throw an error:

etl.postgres.upsert(pool,'public','test',{concurrency:4 })

**Comment by Go2ClassPoorYorick** [comment]
> Awesome, thank you @Go2ClassPoorYorick - can you create or amend a test that would fail on master but work with this fix?

https://github.com/ZJONSSON/node-etl/pull/99/commits/ce61ab0f0644a0acb2c784dc424a6a3e92785dff

Represents a working test

https://github.com/ZJONSSON/node-etl/pull/99/commits/b5eda22716c71349411dcbbea7151c5d65631a3e

Represents a broken test.

**Comment by ZJONSSON** [comment]
Excellen, thank you @Go2ClassPoorYorick

**Comment by ZJONSSON** [comment]
published `+ etl@0.6.8`

**Pull request merged**
