### PR TITLE
Initial Version to gather thoughts | Support for AWS SQS

### PR DESCRIPTION
**Pull request by montumodi**
We had scenario of streaming data from mongo to sqs so many times so I thought may be I could create a new destination. This PR is just to gather thoughts before I spend more time on this. I have updated the readme so you will have enough information. let me know if something is not making sense.

Let me know your thoughts.

### CODE REVIEW

**Comment by montumodi** [comment]
@jbreckman - Whenever you get a chance if you have a look at initial version.

**Comment by ZJONSSON** [comment]
Thanks @montumodi - really appreciate the time you took to submit the PR

My initial take:
Batching is already supported under `etl.collect` and is heavily used in front of the different database upsert/insert functions, such as mysql, postgres, elasticsearch etc.

So the `etl`ish way to do this would be:

```js
const QueueUrl = .....
const sqsClient = .....

getSourceStream() // some function that returns the stream of messages
  .pipe(etl.collect(100))  // assuming we want each batch to be 100 messages
  .pipe(etl.map(5, messageArray => {   // 10 here stands for `concurrency: 5`
    return sqsClient.sendMessageBatch({QueueUrl, messageArray}).promise();
  }))
  .promise();
```

I'm not entirely convinced we need an entire new target for sqs.    We could however have an example of how to leverage `etl` for SQS in the readme?    Let me know if there is anything missing from the example above.

Also, your PR would introduce new dependencies, including `aws-sdk` which is relatively big, and a redundant promise batches (i.e. `batch-promises` vs.  `etl.collect`).   The `etl` package is designed to be very lightweight and the list of dependencies is kept at an absolute minimum:

```
"dependencies": {
    "bluebird": "~3.5.0",
    "csv-parser": "~1.8.0",
    "duplexer2": "~0.1.4",
    "moment": "~2.21.0",
    "streamz": "~1.8.10"
  }
```

**Comment by montumodi** [comment]
Thanks @ZJONSSON for your reply. It kind of makes sense what you explained. I will close this PR for now. May be open a separate one for readme example.

**Comment by jbreckman** [comment]
Agree with @ZJONSSON that package.json shouldn't change.  If you want to add a `sqs` adapter that takes a connection object of some sort and adds some helper batching messages I could see that being useful.

I don't see how this is any different from what the mongodb adapter does.  That adapter is super small and takes a connection object and does simple operations on that.  It could just follow that pattern I think.

In your example, you still have a `collect` above it, but you should probably do that internally to the sqs method I think.  So something like this:
```
etl.file('test.csv')
  .pipe(etl.sqs.bulk(queueUrl, sqsClient, ["someIdKeyName"], {batchSize: 20}));
```

Since you are passing `sqsClient` there is no need for that to be part of the `package.json`

**Comment by montumodi** [comment]
@jbreckman Thanks for your comments. I was thinking on the same line. Will modify and re-open it once done.

**Pull request closed without merging**
